name: Semgrep with Docker

on:
  push:  # Se elimina la restricción de rama específica
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest  # Utiliza la imagen de Docker oficial de Semgrep

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Semgrep
      run: semgrep --config="p/r2c-ci"  # Puedes ajustar esto para usar tus propias reglas o configuraciones



