name: Semgrep with Docker

on:
  push:  # Se activa en cada push a cualquier rama
  pull_request:  # Se activa en cada pull request a cualquier rama

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest  # Utiliza la imagen de Docker oficial de Semgrep

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Semgrep
      run: semgrep --config=./rules/wildcard-cors.yaml --error  # Modificado para usar el flag --error




